FROM node:20

WORKDIR /usr/src/app

COPY ./graphql-subgraph/package.json .
COPY ./graphql-subgraph/yarn.lock .

RUN yarn install --prefer-offline --frozen-lockfile

COPY ./graphql-subgraph .

RUN yarn build

CMD ["yarn", "start"]
